### ISSUE TITLE
Jessie: Configuration > Localisation > Timezone setting ignored

### ISSUE THREAD

**Issue by wardjk** [raspberrypi/rc_gui#10]
After selecting US > Central, the setting goes back to America > Chicago.

**Comment by spl237** [comment]
America->Chicago is the same time zone as US->Central. 

This is an issue with the way time zones are represented in Unix - for some time zones there are numerous ways the same thing can be described. Users can select from any of the possible descriptions to choose one, but what is stored is a single internal value, which is reported back as the first option in the list. Not ideal from a UI point of view, but the alternative is having to store a "displayed time zone" option as well as the actual internal value, which introduces the possibility of them becoming out of sync and creating even more confusion.

**Comment by wardjk** [comment]
One of the following approaches should be taken to compensate for UI shortcomings and prevent this issue from being viewed as a bug:
1. Include a note on the interface explaining that the user's selection will be translated to an equivalent value.
2. Show the translated equivalent value live as the user selects from the list
3. Don't offer values user's can't have.
4. Display the user's selected value on subsequent visits to the setting (already ruled out)

Although Chicago is far from me and other major cities are closer, I'm aware that Chicago is in the same time zone I am but others may not be. The list of cities is long and users may not know of an appropriate selection without tedious comparisons so displaying cities instead of zones can often be cumbersome.
