### ISSUE TITLE
Boot to Desktop/CLI setting doesn't save in some cases

### ISSUE THREAD

**Issue by mrichardson23** [raspberrypi/rc_gui#11]
Steps to reproduce from a fresh install of Raspbian:
 1. open rc_gui
 1. change boot to CLI
 1. expand file system
 1. click OK in main window to save all settings.
 1. say no to reboot
 1. reboot manually

Expecting: Boot to CLI
Actual: Boots to desktop

I'm not sure if it's step 3 or 5 above that causes the issue. I can only really test this when I'm using a fresh install of Raspbian.

**Comment by spl237** [comment]
Known bug - already fixed. Just do a sudo apt-get upgrade on the image before you try to do anything else.

There will be a new image file available for download by the end of November, including this fix.

**Comment by ex-nerd** [comment]
There are still at least a couple missing "else" clauses against `if [ -e /etc/init.d/lightdm ]; then` checks (for B1 and B2).

**Comment by spl237** [comment]
Have you actually noticed the boot to desktop / CLI setting not saving, or is your comment above related to another issue? There are cases where there is no valid "else" behaviour.

**Comment by ex-nerd** [comment]
Just commenting that the code was confusing.  saw the 'else' clauses below and assumed there would be scenarios it should be valid for everything.  Then again, I'm also the guy who puts in a lot of no-op else clauses with comments as to why.

In this case, it reads to me that if lightdm isn't installed (which it isn't on mine), I'd be unable to switch between B1 and B2.  I haven't tested it (my pi is totally headless) but I don't see anywhere else in the code where the getty@.service and autologin@.service (and equivalent non-systemd) stuff is set properly.

**Comment by spl237** [comment]
If lightdm isn't installed, you can't boot to GUI - so the system will be booting to CLI by default, and no action is required in these cases. The GUI config application (which should be the default) checks that lightdm is installed when it is started and refuses to continue otherwise.

**Comment by ex-nerd** [comment]
But the `raspi-config` here is also used via the CLI -- it's replaced the original asb one.

**Comment by ex-nerd** [comment]
Actually, not that I look at it, it might just be that the `if [ -e /etc/init.d/lightdm ]; then` checks for B1 (line 712) and B2 (line 723) could probably just go away.
