### ISSUE TITLE
raspi-config still references asb's git repo

### ISSUE THREAD

**Issue by ex-nerd** [raspberrypi/rc_gui#14]
His repository is definitely out of date compared to the version that I now have on my pi -- it would be nice to add a blurb at the top of the file to note that the file is derived from his, but is actually maintained here.

Took me way longer than it should have to find out where to file a bug report against the version of raspi-config that came with my Raspian Jessie.

**Comment by XECDesign** [comment]
The shipped version comes from RPi-Distro/raspi-config, which now has the correct URL. https://github.com/RPi-Distro/raspi-config/commit/7cd570b63e4babd0d3736f07b9d1723066a35060

**Comment by spl237** [comment]
Now fixed in this repo as well.
