### ISSUE TITLE
Add support for gpu_mem_256, gpu_mem_512, gpu_mem_1024

### ISSUE THREAD

**Issue by gohai** [raspberrypi/rc_gui#24]
Right now, the dialog always shows and modifies the `gpu_mem` variable, even if there is `gpu_mem_*` option set, which takes precedence over `gpu_mem`.

For a graphic-intensive application, we'd love to be able to create a Raspbian remix that increases the default GPU memory by various amounts for the different RAM sizes. `gpu_mem_*` works well for this.

_But_, when the users still run out of graphics memory, and try to increase the split via the Raspberry Pi Configuration, this doesn't work as expected.

**Comment by spl237** [comment]
raspi-config and the GUI have now been modified to read in the current setting (whether from the gpu_mem variable or a gpu_mem_* option if one is set).

When writing, raspi-config will remove any gpu_mem_* variables and only updates the gpu_mem parameter; doing anything else involves trying to guess what the user wants for other platforms, so this is about the best that can be done in this tool.

**Comment by gohai** [comment]
Super, that's great help. Thanks!
