### ISSUE TITLE
Modular Prefrences

### ISSUE THREAD

**Issue by ZanderBrown** [raspberrypi/rc_gui#34]
Now `x86 PIXEL` is a thing we need to be able change the available preferences appropriately for the current system.

I was thinking the easiest way to do this would be to use `libpeas` to create a modular system with a plug-in for each 'page'. The plugins could be marked as for 'Pi' or for 'x86' or both. It would also allow for a simplified configuration system, appearance & audio etc. could remain separate projects but instead of being separate applications provide a module for 'PIXEL Prefrences' allowing everything to be managed from one place

**Comment by spl237** [comment]
Hmm - that's some strange use of the word "easiest" that I haven't seen before... ;)

The _easiest_ thing to do is to use architecture-specific #defines to remove the unwanted controls from the x86 version; that's approximately 10 minutes of work, including the rebuild!

I'm very keen not to overcomplicate a system which works very efficiently as it is; conditional compilation options will do this just fine.
