### ISSUE TITLE
int can_configure -> check pi user exists, renders rc_gui broken an user change?

### ISSUE THREAD

**Issue by drankinatty** [raspberrypi/rc_gui#35]
Devs,

  For the most part, all is well, but with rc_gui, if the default 'pi' user is renamed or deleted, rc_gui fails to run. Specifically, when disabling auto-login and renaming the 'pi' account (to get rid of it, etc.) this causes significant problems with the raspberry-config utility. It seems backwards that a config utility on Linux should require a specific user name before it will run. Why should it care? There are many instances were renaming the user to recover uid=1000 for uid map purposes, etc. will be desired. Having rc_gui hardwired to a 'pi' username causes havok in these cases. Can this requirement be removed so that rc_gui will work for any user (regardless of whether 'pi' exists)?

**Comment by spl237** [comment]
Not trivially. The tool checks for the pi user at startup for a reason! The command-line raspi-config does exactly the same, as there are numerous places where it is much easier to check for one particular user account than to check for various ones.

If a user knows enough to add and remove user accounts (which is not currently possible via the GUI), we are assuming for now that they also have no need of a GUI-based config tool and are happy with using the command line to configure the system (as they will have to have used command line tools to change user accounts).

I'm not saying it is something that we won't look at in future, but the vast majority of users just use the default pi account; it's a fairly large amount of work and retesting to make these tools work on all accounts, and it's not currently a priority.

**Comment by drankinatty** [comment]
I agree with your assessment and the balance of the 'vast majority' against those that want to move/remove the account. Manually managing the links for activating the root account, managing the users, and handling the getty.target.wants symlinks is simple enough. 

The issue I see is this, if the pi account is removed, then the point is -- for every other user created, the rc_gui in the menu is inoperative. (yes this is small in the grand scheme of things, but in the future it is well worth another look to decouple the pi account from any configuration requirements -- it is a limitation that need not exist)

In close, let me give you and all of the rest of the devs here and a debian a -- 'job well done' adulation. Everything works remarkably well on the credit-card sized box. If the hardware folks could ever put a SSD M.2 slot on the back -- this thing would fly.
