### ISSUE TITLE
time-zone location combobox visual glithes

### ISSUE THREAD

**Issue by beta-tester** [raspberrypi/rc_gui#5]
similar to this remote screenshot...
<img width="345" alt="unknown" src="https://cloud.githubusercontent.com/assets/4750719/10267168/58bb219a-6a89-11e5-8acc-a0a4dd1398e6.PNG">
but the issue is the same on GUI of Raspbian directly.

if i open the location combobox, the top half of the list is initially empty, until i scroll further down.
i am not very familar with the Linux GUI, but i expected that the list would be filled up to the top initially.
i could observe that issue only on that combobox, but maybe it is coincidentally, because of the content of my selections. (Area: Europe)

**Comment by spl237** [comment]
Believe it or not, this is known and desired behaviour in the GTK toolkit - there have been numerous patches pushed to GTK to change it over the last few years and all have been rejected. I agree it doesn't look good, but it is how GTK is supposed to work.

**Comment by beta-tester** [comment]
oooh thats funny ...
but why i can see that behaviour only at the Location combobox?
all others are initially filled fully up to the top (e.g. Area combobox)

anyhow... it is only an cosmetically issue and i don't change the settings that often, once my favorite  settings are and stays persistent. ;)

**Comment by spl237** [comment]
It depends on the number of items to put into the list - you only see it with comboboxes with large numbers of items to choose from and in which the currently-selected item is near one end of the list...

**Comment by beta-tester** [comment]
ah, ok... then now i understand.
