### ISSUE TITLE
Jessie: Configuration > Localisation > Keyboard setting ignored

### ISSUE THREAD

**Issue by wardjk** [raspberrypi/rc_gui#9]
Some list indexes are ignored and not saved. Go to Raspberry Pi Configuration > Localisation > Set Keyboard > Select Country = United States > Variant = English (US) > OK > OK. Open same setting again and find that Variant = Spanish (Latin America) is selected instead. I first thought this bug was caused by list index 0 being disallowed but found other Variants in the list that were not saved and the selection went back to Spanish (Latin America) (list index 1). Some selections mid-way in the list can be saved but not the first and last.

I was asked to post this issue in https://github.com/raspberrypi/rc_gui/issues

**Comment by spl237** [comment]
The US English keyboard driver is the same as that used for Latin America / Spanish.

This is an issue with the way keyboard drivers are represented in Unix - for some keyboard drivers there are numerous ways the same thing can be described. Users can select from any of the possible descriptions to choose one, but what is stored is a single internal value, which is reported back as the first option in the list. Not ideal from a UI point of view, but the alternative is having to store a "displayed keyboard" option as well as the actual internal value, which introduces the possibility of them becoming out of sync and creating even more confusion. 

(And yes, there is a reason this paragraph is basically a cut-and-paste of that I wrote for the time zone issue you reported; it's exactly the same issue but in a different area!)

**Comment by wardjk** [comment]
I did not know they were the same. Why not call it "US English" instead of "Spanish (Latin America)"? By doing so, would a greater majority of Spanish (Latin America) speaking users be confused with the problem?

**Comment by spl237** [comment]
It's not a choice I make - when the UI parses the list of available drivers, the first name that matches the selected driver is Spanish (Latin America), so that's the one which is shown.

As above - the only fix is to separately store the UI setting and try to keep it in sync with the internal setting, which would be tedious and prone to error.
